New design for ngo register
code4moldova/ajut.md pull request #34
Opened 2021-10-22 10:14 UTC by vitaliel

Closes #11

2021-10-22 10:15 UTC, vitaliel commented
How it looks:
![ngo-reg-form](https://user-images.githubusercontent.com/995/138437249-5557cea7-d5e2-4acb-904c-dfc2c25502ea.png)

2021-10-26 16:30 UTC, alexkingdom requested changes
As I saw you have two PRs with same changes or at least part of changes are same, I commented in both cases, but after we will migrate one of your PR, you will rebase so we will see what you made in PR.

2021-10-26 16:30 UTC, alexkingdom commented on ro_help/hub/templates/ngo/register_request.html
> +                <h1>Înregistrare ONG</h1>
Seems we need to translate this string

2021-10-26 16:30 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"распространенияCovid-19. Основная цель палтформы - помочь организациям "
Typo

2021-10-26 16:30 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"былаиспользована. Запросите новый сброс пароля."
Typo

2021-10-26 16:30 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"отношенииобработки персональных данных Code for Moldova, вы можете связаться "
Typo

2021-10-26 16:30 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"в этот период! Любая помощь увеличивает наши возможностиделать добро "
Typo

2021-10-26 16:30 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"поддержку в это время! Любая помощь увеличивает нашуспособность творить "
Typo

2021-10-27 08:12 UTC, alexkingdom approved these changes

2021-10-27 08:13 UTC, alexkingdom commented
PR is ok for me, waiting for @johnsmithm to see if also is ok, so we can merge it.
Thank you very much for contributing!

2021-11-03 15:20 UTC, merged