New design for home page with filters
code4moldova/ajut.md pull request #35
Opened 2021-10-26 14:47 UTC by vitaliel

It depends on https://github.com/code4moldova/ajut.md/pull/34

Closes #4

It looks like:
![Screenshot 2021-10-26 at 17-42-57 Luptă împotriva pandemiei de Covid-19 ](https://user-images.githubusercontent.com/995/138903641-2d1222e7-cfa5-42de-b128-e3bfdcb0115b.png)

2021-10-26 15:11 UTC, alexkingdom commented on ro_help/ro_help/settings/base.py
> +DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", "noreply@rohelp.ro")
@johnsmithm I think we need to adjust the email in all places, what do you think ?

2021-10-26 16:23 UTC, alexkingdom requested changes

2021-10-26 16:23 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"былаиспользована. Запросите новый сброс пароля."
Typo

2021-10-26 16:23 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"отношенииобработки персональных данных Code for Moldova, вы можете связаться "
Typo

2021-10-26 16:23 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"в этот период! Любая помощь увеличивает наши возможностиделать добро "
Typo

2021-10-26 16:23 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"поддержку в это время! Любая помощь увеличивает нашуспособность творить "
Typo

2021-10-26 16:23 UTC, alexkingdom commented on ro_help/locale/ru/LC_MESSAGES/django.po
> +"распространенияCovid-19. Основная цель палтформы - помочь организациям "
Typo ?

2021-10-26 16:23 UTC, alexkingdom commented
Basically seems all is good just some typo errors

2021-10-27 06:30 UTC, vitaliel commented
@alexkingdom typos are from PR 34 that I used as base. I fixed them and when 34 will be merged, this PR should look fine.

2021-10-27 08:15 UTC, alexkingdom approved these changes

2021-11-03 15:21 UTC, alexkingdom commented
@vitaliel Please update your PR and fix conflicts 😃

2021-11-03 15:54 UTC, vitaliel commented
@alexkingdom fixed, it was binary file of gettext. I'm not a fun of storing generated mo files in repository.

2021-11-03 16:41 UTC, merged